[package]
name = "coloring_common"
version = "1.0.0"
edition = "2021"

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
